//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveSplit.Racetime.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveSplit.Racetime.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap con_green {
            get {
                object obj = ResourceManager.GetObject("con_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap con_red {
            get {
                object obj = ResourceManager.GetObject("con_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die / ähnelt.
        /// </summary>
        internal static string CREATE_RACE_ADDRESS {
            get {
                return ResourceManager.GetString("CREATE_RACE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die racetime.gg ähnelt.
        /// </summary>
        internal static string DOMAIN {
            get {
                return ResourceManager.GetString("DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die races/data ähnelt.
        /// </summary>
        internal static string ENDPOINT_RACES {
            get {
                return ResourceManager.GetString("ENDPOINT_RACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f {
            get {
                object obj = ResourceManager.GetObject("f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flag {
            get {
                object obj = ResourceManager.GetObject("flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap live {
            get {
                object obj = ResourceManager.GetObject("live", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap live_and_ready {
            get {
                object obj = ResourceManager.GetObject("live_and_ready", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap not_live {
            get {
                object obj = ResourceManager.GetObject("not_live", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S256 ähnelt.
        /// </summary>
        internal static string OAUTH_CHALLENGE_METHOD {
            get {
                return ResourceManager.GetString("OAUTH_CHALLENGE_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die dKgJFc2jZjgMtUT4Ik9kyJSCZkVqRK1poCcvpKox ähnelt.
        /// </summary>
        internal static string OAUTH_CLIENTID {
            get {
                return ResourceManager.GetString("OAUTH_CLIENTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rl6gGXy9zPw5xkSa0gSdE69lnlqbTwuZDAFNSDTgY5QKbQ9AqsqDYlotNGMBboDGkZFbJm9fSIpfI3sCGc3UiiZ2sEpk8KpxYf4kh0G7TjmYmgn0AXyNJNzkgIorHAcB ähnelt.
        /// </summary>
        internal static string OAUTH_CLIENTSECRET {
            get {
                return ResourceManager.GetString("OAUTH_CLIENTSECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die o/authorize ähnelt.
        /// </summary>
        internal static string OAUTH_ENDPOINT_AUTHORIZATION {
            get {
                return ResourceManager.GetString("OAUTH_ENDPOINT_AUTHORIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die o/done?error=access_denied ähnelt.
        /// </summary>
        internal static string OAUTH_ENDPOINT_FAILURE {
            get {
                return ResourceManager.GetString("OAUTH_ENDPOINT_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die o/revoke_token ähnelt.
        /// </summary>
        internal static string OAUTH_ENDPOINT_REVOKE {
            get {
                return ResourceManager.GetString("OAUTH_ENDPOINT_REVOKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die o/done ähnelt.
        /// </summary>
        internal static string OAUTH_ENDPOINT_SUCCESS {
            get {
                return ResourceManager.GetString("OAUTH_ENDPOINT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die o/token ähnelt.
        /// </summary>
        internal static string OAUTH_ENDPOINT_TOKEN {
            get {
                return ResourceManager.GetString("OAUTH_ENDPOINT_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die o/userinfo ähnelt.
        /// </summary>
        internal static string OAUTH_ENDPOINT_USERINFO {
            get {
                return ResourceManager.GetString("OAUTH_ENDPOINT_USERINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 127.0.0.1 ähnelt.
        /// </summary>
        internal static string OAUTH_REDIRECT_ADDRESS {
            get {
                return ResourceManager.GetString("OAUTH_REDIRECT_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 4888 ähnelt.
        /// </summary>
        internal static string OAUTH_REDIRECT_PORT {
            get {
                return ResourceManager.GetString("OAUTH_REDIRECT_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die read chat_message race_action ähnelt.
        /// </summary>
        internal static string OAUTH_SCOPES {
            get {
                return ResourceManager.GetString("OAUTH_SCOPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://racetime.gg/ ähnelt.
        /// </summary>
        internal static string OAUTH_SERVER {
            get {
                return ResourceManager.GetString("OAUTH_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0.7 ähnelt.
        /// </summary>
        internal static string PLUGIN_VERSION {
            get {
                return ResourceManager.GetString("PLUGIN_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https ähnelt.
        /// </summary>
        internal static string PROTOCOL_REST {
            get {
                return ResourceManager.GetString("PROTOCOL_REST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die wss ähnelt.
        /// </summary>
        internal static string PROTOCOL_WEBSOCKET {
            get {
                return ResourceManager.GetString("PROTOCOL_WEBSOCKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://github.com/steto-scope/LiveSplit.Racetime/releases/download/ ähnelt.
        /// </summary>
        internal static string UPDATE_DATA {
            get {
                return ResourceManager.GetString("UPDATE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://steto-scope.github.io/LiveSplit.Racetime/update.racetime.xml ähnelt.
        /// </summary>
        internal static string UPDATE_DEFINITION {
            get {
                return ResourceManager.GetString("UPDATE_DEFINITION", resourceCulture);
            }
        }
    }
}
